### ISSUE TITLE
Without modifications in framework and services

### ISSUE THREAD

**Issue by maxMaxim59** [Jefino9488/FrameworkPatcher#1]
I tried to core patch the HyperOS A13 Global files and did not get any modifications in framework.jar and services.jar

In the log build the warning appeared that the necessary smalis and folders were not found or did not exist

![Screenshot_2024-07-03-17-45-15-721_com microsoft emmx](https://github.com/Jefino9488/FrameworkPatcher/assets/62408960/cf1a065d-ea14-41c7-85e1-d5797fc01f8b)
![Screenshot_2024-07-03-17-45-25-310_com microsoft emmx](https://github.com/Jefino9488/FrameworkPatcher/assets/62408960/68c74272-9471-4d57-b43e-e4c6607de0aa)

**Comment by Jefino9488** [comment]
Thanks for info will look into it

**Comment by Jefino9488** [comment]
could u test again now

**Comment by N0nd** [comment]
Why not add support for miui A12!?

**Comment by Jefino9488** [comment]
> Why not add support for miui A12!?

may add further / in future or may not

**Comment by Jefino9488** [comment]
## Issue is fixed

thanks for reporting
