### ISSUE TITLE
Recompilation issues on HyperOS A13 (SDK 33)

### ISSUE THREAD

**Issue by riarumoda** [Jefino9488/FrameworkPatcher#10]
Hi i'm trying to use your github action services to patch a13 hyperos framework but when recompiling this appears:
https://github.com/Jefino9488/FrameworkPatcher/actions/runs/10340536984/job/28621275618
![image](https://github.com/user-attachments/assets/6ee79402-ec0a-4317-90cc-707dad5a0478)
the files that i've been trying to patch is in here:
https://dumps.tadiphone.dev/dumps/qti/veux/-/raw/missi_phoneext4_cn-user-13-TKQ1.221114.001-V816.0.1.0.TKCCNXM-release-keys/system/system/framework/framework.jar?inline=false
https://dumps.tadiphone.dev/dumps/qti/veux/-/raw/missi_phoneext4_cn-user-13-TKQ1.221114.001-V816.0.1.0.TKCCNXM-release-keys/system/system/framework/services.jar?inline=false
https://dumps.tadiphone.dev/dumps/qti/veux/-/raw/missi_phoneext4_cn-user-13-TKQ1.221114.001-V816.0.1.0.TKCCNXM-release-keys/system_ext/framework/miui-framework.jar?inline=false
https://dumps.tadiphone.dev/dumps/qti/veux/-/raw/missi_phoneext4_cn-user-13-TKQ1.221114.001-V816.0.1.0.TKCCNXM-release-keys/system_ext/framework/miui-services.jar?inline=false

**Comment by Jefino9488** [comment]
aware of it will look into it after

**Comment by Jefino9488** [comment]
The issue should be fixed by this [comit](https://github.com/Jefino9488/FrameworkPatcher/commit/3d22e17593c9363fbc37cda2e701c37d0f71cc53) retry build.Let me know if it continues.

**Comment by Jefino9488** [comment]
the issue should be fixed by this [comit](https://github.com/Jefino9488/FrameworkPatcher/commit/3d22e17593c9363fbc37cda2e701c37d0f71cc53) retry build.Let me know if it continues.
