### ISSUE TITLE
[Xiaomi 11 Lite 5G NE] Testers Needed

### ISSUE THREAD

**Issue by joeyoropesa-dev** [Jefino9488/FrameworkPatcher#11]
To low potential risks during production, please everyone who is using this phone on stock ROM (Global ROM), please look into this module and report here is there any issues with it. If there is no issues, please comment "success" and this issue will be closed. (This issue is currently closed not because it's completed but it's because of repo owner's attitude)

Thanks in advance! ✨

[modded_lisa_V1.0.5.0.UKOMIXM.zip](https://github.com/Jefino9488/FrameworkPatcher/releases/tag/V1.0.5.0.UKOMIXM)

**Comment by Jefino9488** [comment]
test ur self bro

**Comment by joeyoropesa-dev** [comment]
> test ur self bro

I don't wanna risk and make my device unusable and bricked - if someone wants to do it, I've opened issue for that.

I know clearly what root and unlocking bootloader means so.. no

Instead of risking directly and brick something in my device and losing my data, I will count on people who actually wants to risk and have same device as me.
