### ISSUE TITLE
suggestion for an exectuable to do it manually on our own system than rely on device backups that dont have devices me might have

### ISSUE THREAD

**Issue by ghost** [Jefino9488/FrameworkPatcher#15]

**Comment by fuengfah** [comment]
totally agree onnthis issue

**Comment by Jefino9488** [comment]
can make executable for Linux but I doubt for windows

**Comment by ghost** [comment]
> can make executable for Linux but I doubt for windows

a person can use WSL

**Comment by Jefino9488** [comment]
hmm , i can make local executable script
