### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by aconk168** [Jefino9488/FrameworkPatcher#17]
this mod not working..iam flashing the module than i reboot my device....the result os stuck in Mi logo...

**Comment by Jefino9488** [comment]
was it fixed ? or booted ?

**Comment by aconk168** [comment]
still stuck on mi logo bro..

**Comment by aconk168** [comment]
this mod make device stuck on mi logo...please fixed it my bro

**Comment by Jefino9488** [comment]
give more info , rom version , android versions , those jars used to build

**Comment by russel5** [comment]
Xiaomi 14 Ultra hyper 2.0 all works, phone boots up.
Thanks for your support

**Comment by Jefino9488** [comment]
closing because no additional info provided
