### ISSUE TITLE
Crash LatinImeGoogle.apk (GBoard)

### ISSUE THREAD

**Issue by maxMaxim59** [Jefino9488/FrameworkPatcher#2]
When getting the job on A13 HyperOS, GBoard crashes, for no reason. MT Manager does not work properly, the internal, external and root storage pages are blank, the problem is that it does not take permission to show the device files. SwiftBackup also crashes for no reason. Unfortunately for the MT and SwiftBackup bug there is no log.

[system_app_crash@LatinImeGoogle.txt](https://github.com/user-attachments/files/16100362/system_app_crash%40LatinImeGoogle.txt)

**Comment by Jefino9488** [comment]
ahh rebuild may fix if not report

**Comment by maxMaxim59** [comment]
Still not working. I really don't know what could be causing it.

**Comment by Jefino9488** [comment]
hmm removing module fixes it ?

**Comment by maxMaxim59** [comment]
Removing the module, yes

**Comment by khanhkhokhao** [comment]
Same case on HyperOS A14 #Nuwa

**Comment by Jefino9488** [comment]
should be fixed by now

**Comment by Jefino9488** [comment]
should be fixed now
