### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by ammlr** [Jefino9488/FrameworkPatcher#6]
![Screenshot_2024-07-13-09-16-12-106_com android chrome](https://github.com/user-attachments/assets/a1c0f9bd-21ed-475f-99a3-c894dac429cc)I 
I don't know why this happens in hyperos global 1.0.2.0

**Comment by khanhkhokhao** [comment]
> ![Ảnh chụp màn hình_2024-07-13-09-16-12-106_com android chrome](https://private-user-images.githubusercontent.com/30746607/348443734-a1c0f9bd-21ed-475f-99a3-c894dac429cc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MTk2NTQsIm5iZiI6MTcyMDkxOTM1NCwicGF0aCI6Ii8zMDc0NjYwNy8zNDg0NDM3MzQtYTFjMGY5YmQtMjFlZC00NzVmLTk5YTMtYzg5NGRhYzQyOWNjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDAxMDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZmI3ZTkwZGI5MWNlZWE4ZDk2NGI3ZGRjNmMyYTM5YjVmYzUxZjE3ZmI3NDA0MjRlOWNmZGNiODk3ODYxYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BDY3lYXkq93uzZ1hlYVh4L6ukmOnC0GRec1o-GE85iA)Tôi không biết tại sao điều này lại xảy ra trong hyperos global 1.0.2.0

Let's use gitlab as a repository for 4 .jar files

**Comment by Jefino9488** [comment]
will look into it

**Comment by Jefino9488** [comment]
the issue should be fixed by this [comit](https://github.com/Jefino9488/FrameworkPatcher/commit/3d22e17593c9363fbc37cda2e701c37d0f71cc53) retry build.
